#!/bin/bash
# Browser-based test for nested site creation
# This script documents the manual testing process using browser MCP

set -e

echo "🧪 Browser-Based Nested Site Creation Test"
echo "==========================================="
echo ""
echo "This test verifies the nested site creation UI and functionality."
echo ""
echo "📋 Test Steps:"
echo ""
echo "1. Navigate to: https://site3.localwp/wp-admin/network/site-new.php"
echo "2. Verify 'IdeAI: Nested Site Options' section appears"
echo "3. Verify 'Parent site' dropdown is visible and at the top"
echo "4. Select a parent site (e.g., 'Network root (/)')"
echo "5. Verify nested fields appear:"
echo "   - Grayed-out prefix showing parent path"
echo "   - Child slug input field"
echo "   - Full URL preview"
echo "6. Enter a child slug (e.g., 'test123')"
echo "7. Verify full URL preview updates correctly"
echo "8. Click 'Add Site' button"
echo "9. Verify site is created with correct nested path"
echo "10. Navigate to the new site's admin"
echo "11. Verify all admin URLs use correct nested path (no --)"
echo ""
echo "✅ Expected Results:"
echo "  - Site created at: https://site3.localwp/parent/test123/"
echo "  - Admin URL: https://site3.localwp/parent/test123/wp-admin/"
echo "  - No -- in any URLs"
echo "  - All links point to correct nested site"
echo ""
echo "🔍 Verification Commands:"
echo ""
echo "# Check database path"
echo "docker-compose -f docker-compose.flexible.yml exec db3 mysql -u root -proot wordpress3 -e \"SELECT blog_id, path FROM wp_blogs WHERE path LIKE '%test123%';\""
echo ""
echo "# Check nested tree mapping"
echo "docker-compose -f docker-compose.flexible.yml exec db3 mysql -u root -proot wordpress3 -e \"SELECT blog_id, path FROM wp_ideai_nested_tree_paths WHERE path LIKE '%test123%';\""
echo ""
echo "# Test URL accessibility"
echo "curl -k -I https://site3.localwp/parent/test123/wp-admin/"
echo ""
echo "📝 Manual Browser Testing:"
echo "  Use Cursor's browser MCP tools to:"
echo "  1. Navigate to site creation page"
echo "  2. Interact with nested site fields"
echo "  3. Create a test site"
echo "  4. Verify URLs are correct"
echo ""
echo "Ready for browser testing! 🚀"

