#!/bin/bash
set -euo pipefail

# Enables LOCAL HTTPS for the docker-compose.flexible.yml stack using mkcert.
#
# What it does:
# - Generates a single cert valid for localhost + site*.local (+ wildcard for site2 subdomains)
# - Writes an nginx HTTPS config file into nginx/conf.d/https/
# - Restarts nginx
#
# Requirements:
# - mkcert installed (macOS: `brew install mkcert nss`)
#
# Usage:
#   ./scripts/dev/setup-https-mkcert.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CERT_DIR="$ROOT_DIR/nginx/certs"
HTTPS_CONF_DIR="$ROOT_DIR/nginx/conf.d/https"
CERT_FILE="$CERT_DIR/local-dev.pem"
KEY_FILE="$CERT_DIR/local-dev-key.pem"
HTTPS_CONF_FILE="$HTTPS_CONF_DIR/https.local.conf"

echo "🔐 Enabling local HTTPS (mkcert)"
echo ""

if ! command -v mkcert >/dev/null 2>&1; then
  echo "❌ mkcert not found."
  echo ""
  echo "Install on macOS:"
  echo "  brew install mkcert nss"
  echo "  mkcert -install"
  exit 1
fi

mkdir -p "$CERT_DIR" "$HTTPS_CONF_DIR"

echo "1) Ensuring local CA is installed (mkcert -install)"
mkcert -install >/dev/null

echo "2) Generating certificate:"
echo "   - $CERT_FILE"
echo "   - $KEY_FILE"

# .localwp domains + wildcard for Site 2 subdomains.
mkcert \
  -cert-file "$CERT_FILE" \
  -key-file "$KEY_FILE" \
  localhost 127.0.0.1 ::1 \
  site1.localwp \
  site2.localwp "*.site2.localwp" \
  site3.localwp \
  >/dev/null

echo "3) Writing nginx HTTPS config: $HTTPS_CONF_FILE"
cat > "$HTTPS_CONF_FILE" <<'NGINX'
# AUTOGENERATED by scripts/dev/setup-https-mkcert.sh
# Safe to delete; rerun the script to recreate.

ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers off;

# Dashboard over HTTPS
server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/certs/local-dev.pem;
    ssl_certificate_key /etc/nginx/certs/local-dev-key.pem;

    root /var/www/dashboard;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Browse shared wp-content (read-only)
    # Nginx mounts repo ./wp-content to /var/www/shared-wp-content
    location ^~ /shared-content/ {
        alias /var/www/shared-wp-content/;
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
    }
}

# Site 1 over HTTPS (single site example)
server {
    listen 443 ssl;
    server_name site1.localwp;

    ssl_certificate     /etc/nginx/certs/local-dev.pem;
    ssl_certificate_key /etc/nginx/certs/local-dev-key.pem;

    root /var/www/site1;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ^~ /wp-content/ {
        alias /var/www/shared-wp-content/;
        expires 1h;
        add_header Cache-Control "public";
        access_log off;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress1;
        fastcgi_index index.php;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /var/www/html;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        # Tell PHP/WP the original scheme is HTTPS
        fastcgi_param HTTPS on;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;

        fastcgi_param HTTP_HOST $host;
        fastcgi_param SERVER_NAME $server_name;
    }
}

# Site 2 over HTTPS (subdomain multisite example)
server {
    listen 443 ssl;
    server_name site2.localwp *.site2.localwp;

    ssl_certificate     /etc/nginx/certs/local-dev.pem;
    ssl_certificate_key /etc/nginx/certs/local-dev-key.pem;

    root /var/www/site2;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ^~ /wp-content/ {
        alias /var/www/shared-wp-content/;
        expires 1h;
        add_header Cache-Control "public";
        access_log off;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress2;
        fastcgi_index index.php;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /var/www/html;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_param HTTPS on;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;

        fastcgi_param HTTP_HOST $host;
        fastcgi_param SERVER_NAME $server_name;
    }
}

# Site 3 over HTTPS (subdirectory multisite example)
server {
    listen 443 ssl;
    server_name site3.localwp;

    ssl_certificate     /etc/nginx/certs/local-dev.pem;
    ssl_certificate_key /etc/nginx/certs/local-dev-key.pem;

    root /var/www/site3;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ^~ /wp-content/ {
        alias /var/www/shared-wp-content/;
        expires 1h;
        add_header Cache-Control "public";
        access_log off;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress3;
        fastcgi_index index.php;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /var/www/html;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_param HTTPS on;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;

        fastcgi_param HTTP_HOST $host;
        fastcgi_param SERVER_NAME $server_name;
    }
}
NGINX

echo "4) Restarting nginx container"
cd "$ROOT_DIR"
docker compose -f docker-compose.flexible.yml restart nginx >/dev/null

echo ""
echo "✅ HTTPS enabled."
echo ""
echo "Try:"
echo "  https://localhost"
echo "  https://site1.localwp/wp-admin/install.php"
echo "  https://site2.localwp/wp-admin/install.php"
echo "  https://site3.localwp/wp-admin/install.php"


